import prisma from '../src/lib/db/prisma';

const opportunities = [
  {
    title: 'Chevening Scholarship',
    sponsor: 'UK Foreign, Commonwealth & Development Office',
    orgType: 'government',
    hostCountry: 'United Kingdom',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'India', 'Pakistan', 'Bangladesh', 'South Africa', 'Tanzania', 'Uganda', 'Zimbabwe'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: true, stipendAmount: '£1,133/month' },
    deadline: new Date('2026-11-05'),
    opensDate: new Date('2026-08-06'),
    applyUrl: 'https://www.chevening.org/scholarships/',
    sourceUrl: 'https://www.chevening.org/scholarships/',
    sourceDomain: 'chevening.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Chevening offers a unique opportunity for future leaders, influencers, and decision-makers to develop professionally and academically, network extensively, and build lasting positive relationships with the UK.',
    eligibility: 'Minimum 2 years work experience, return to home country for 2 years, bachelor\'s degree, meet English language requirements.',
    tags: ['leadership', 'fully-funded', 'uk', 'masters', 'work-experience-required'],
  },
  {
    title: 'DAAD EPOS Scholarship',
    sponsor: 'German Academic Exchange Service (DAAD)',
    orgType: 'government',
    hostCountry: 'Germany',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'Ethiopia', 'Tanzania', 'India', 'Pakistan', 'Bangladesh', 'Indonesia', 'Vietnam'],
    disciplines: ['Engineering', 'Computer Science', 'Public Health', 'Agriculture', 'Economics', 'Environmental Science'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: '€934/month' },
    deadline: new Date('2026-10-15'),
    applyUrl: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
    sourceUrl: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/epos/',
    sourceDomain: 'daad.de',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'DAAD EPOS scholarships support graduates from developing countries who wish to earn a postgraduate degree at a German university. Priority given to candidates with 2+ years professional experience.',
    eligibility: 'Bachelor\'s degree, minimum 2 years professional experience, from a developing country, max 6 years since last degree.',
    tags: ['development', 'fully-funded', 'germany', 'masters', 'work-experience-required'],
  },
  {
    title: 'Fulbright Foreign Student Program',
    sponsor: 'U.S. Department of State',
    orgType: 'government',
    hostCountry: 'United States',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'South Africa', 'Ethiopia', 'Egypt', 'India', 'Indonesia', 'Brazil'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: true, stipendAmount: '$1,800-2,500/month' },
    deadline: new Date('2027-02-15'),
    applyUrl: 'https://foreign.fulbrightonline.org/',
    sourceUrl: 'https://foreign.fulbrightonline.org/',
    sourceDomain: 'fulbrightonline.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Fulbright Foreign Student Program enables graduate students, young professionals, and artists from abroad to study and conduct research in the United States.',
    eligibility: 'Bachelor\'s degree, strong academic record, English proficiency, must return to home country for 2 years.',
    tags: ['fully-funded', 'usa', 'masters', 'phd', 'research'],
  },
  {
    title: 'Erasmus Mundus Joint Master Degrees',
    sponsor: 'European Commission',
    orgType: 'government',
    hostCountry: 'Europe (Multiple Countries)',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: '€1,400/month' },
    deadline: new Date('2027-01-15'),
    applyUrl: 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters',
    sourceUrl: 'https://erasmus-plus.ec.europa.eu/',
    sourceDomain: 'ec.europa.eu',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Erasmus Mundus Joint Master Degrees are prestigious, integrated, international study programmes jointly delivered by an international consortium of higher education institutions from different countries worldwide.',
    eligibility: 'Bachelor\'s degree, strong academic record. Open to students from all countries worldwide.',
    tags: ['fully-funded', 'europe', 'masters', 'international', 'consortium'],
  },
  {
    title: 'Commonwealth Scholarship (UK)',
    sponsor: 'Commonwealth Scholarship Commission',
    orgType: 'government',
    hostCountry: 'United Kingdom',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Uganda', 'Tanzania', 'Zambia', 'Malawi', 'Sierra Leone'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: '£1,236/month (London) or £1,043/month' },
    deadline: new Date('2026-12-19'),
    applyUrl: 'https://cscuk.fcdo.gov.uk/scholarships/',
    sourceUrl: 'https://cscuk.fcdo.gov.uk/scholarships/',
    sourceDomain: 'cscuk.fcdo.gov.uk',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'For talented and motivated individuals who have the potential to make change. You must be a citizen of or have been granted refugee status by an eligible Commonwealth country.',
    eligibility: 'Commonwealth citizen, bachelor\'s degree with at least upper second class (2:1) honours, cannot have studied for a year or more in a developed country.',
    tags: ['fully-funded', 'uk', 'masters', 'phd', 'commonwealth'],
  },
  {
    title: 'Gates Cambridge Scholarship',
    sponsor: 'Bill & Melinda Gates Foundation',
    orgType: 'ngo',
    hostCountry: 'United Kingdom',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: '£21,000/year' },
    deadline: new Date('2026-12-03'),
    applyUrl: 'https://www.gatescambridge.org/apply/',
    sourceUrl: 'https://www.gatescambridge.org/',
    sourceDomain: 'gatescambridge.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Gates Cambridge Scholarships are awarded to outstanding applicants from countries outside the UK to pursue a full-time postgraduate degree at the University of Cambridge.',
    eligibility: 'Outstanding academic record, clear research proposal, strong fit with Gates Cambridge\'s mission.',
    tags: ['fully-funded', 'uk', 'cambridge', 'masters', 'phd', 'prestigious'],
  },
  {
    title: 'Australia Awards Scholarships',
    sponsor: 'Department of Foreign Affairs and Trade (DFAT)',
    orgType: 'government',
    hostCountry: 'Australia',
    eligibleCountries: ['Indonesia', 'Vietnam', 'Philippines', 'Papua New Guinea', 'Timor-Leste', 'Mongolia', 'Fiji', 'Samoa', 'Tonga', 'Kenya', 'Ethiopia'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: true, stipendAmount: 'AUD 3,500/month' },
    deadline: new Date('2027-04-30'),
    applyUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships',
    sourceUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards/',
    sourceDomain: 'dfat.gov.au',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Australia Awards Scholarships are long term awards administered by the Department of Foreign Affairs and Trade. They aim to contribute to the development needs of Australia\'s partner countries.',
    eligibility: 'Citizen of a participating country, meet the academic requirements, not have existing Australian visa, minimum 2 years work experience preferred.',
    tags: ['fully-funded', 'australia', 'masters', 'phd', 'development'],
  },
  {
    title: 'Mastercard Foundation Scholars Program',
    sponsor: 'Mastercard Foundation',
    orgType: 'ngo',
    hostCountry: 'Multiple (US, Canada, UK, Africa)',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'Rwanda', 'Uganda', 'Ethiopia', 'Tanzania', 'Senegal', 'South Africa', 'Cameroon', 'Malawi'],
    disciplines: ['STEM', 'Business', 'Social Sciences', 'Public Health', 'Agriculture', 'Education'],
    degreeLevel: ['bachelors', 'masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: true, visa: true, stipendAmount: 'Varies by institution' },
    deadline: new Date('2027-01-31'),
    applyUrl: 'https://mastercardfdn.org/all/scholars/',
    sourceUrl: 'https://mastercardfdn.org/all/scholars/',
    sourceDomain: 'mastercardfdn.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Mastercard Foundation Scholars Program provides academically talented yet economically disadvantaged young people in Africa with access to quality education and development opportunities.',
    eligibility: 'African national, demonstrate financial need, strong academic record, leadership potential, commitment to giving back to community.',
    tags: ['fully-funded', 'africa', 'bachelors', 'masters', 'leadership', 'financial-need'],
  },
  {
    title: 'MEXT Japanese Government Scholarship',
    sponsor: 'Ministry of Education, Culture, Sports, Science and Technology (MEXT)',
    orgType: 'government',
    hostCountry: 'Japan',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['bachelors', 'masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: '¥143,000-145,000/month' },
    deadline: new Date('2027-04-15'),
    applyUrl: 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-702.html',
    sourceUrl: 'https://www.studyinjapan.go.jp/en/',
    sourceDomain: 'studyinjapan.go.jp',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The MEXT Scholarship is offered by the Japanese Government to international students who wish to study at Japanese universities as undergraduate or research students.',
    eligibility: 'Under 35 years old for research students. GPA of at least 2.3 on a 3.0 scale. Must be willing to learn Japanese.',
    tags: ['fully-funded', 'japan', 'bachelors', 'masters', 'phd', 'asia'],
  },
  {
    title: 'Korean Government Scholarship Program (KGSP/GKS)',
    sponsor: 'National Institute for International Education (NIIED)',
    orgType: 'government',
    hostCountry: 'South Korea',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['bachelors', 'masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: '₩1,000,000/month' },
    deadline: new Date('2027-03-31'),
    applyUrl: 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do',
    sourceUrl: 'https://www.studyinkorea.go.kr/en/',
    sourceDomain: 'studyinkorea.go.kr',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Korean Government Scholarship Program (GKS) provides international students with opportunities to conduct advanced studies at higher educational institutions in Korea.',
    eligibility: 'Under 25 for undergraduate, under 40 for graduate. GPA 80%+ in previous degree. Must not hold Korean citizenship.',
    tags: ['fully-funded', 'south-korea', 'bachelors', 'masters', 'phd', 'asia'],
  },
  {
    title: 'Chinese Government Scholarship (CSC)',
    sponsor: 'China Scholarship Council (CSC)',
    orgType: 'government',
    hostCountry: 'China',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['bachelors', 'masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: false, living: true, insurance: true, accommodation: true, visa: false, stipendAmount: 'CNY 3,000-3,500/month' },
    deadline: new Date('2027-03-01'),
    applyUrl: 'https://www.campuschina.org/scholarships/index.html',
    sourceUrl: 'https://www.campuschina.org/',
    sourceDomain: 'campuschina.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Chinese Government Scholarships are established by the Ministry of Education of China to support international students to study at Chinese universities and colleges.',
    eligibility: 'Non-Chinese citizen, good health, valid passport. Under 25 for bachelors, under 35 for masters, under 40 for PhD.',
    tags: ['fully-funded', 'china', 'bachelors', 'masters', 'phd', 'asia'],
  },
  {
    title: 'Swiss Government Excellence Scholarships',
    sponsor: 'Swiss Confederation',
    orgType: 'government',
    hostCountry: 'Switzerland',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['phd', 'postdoc'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: 'CHF 1,920/month' },
    deadline: new Date('2026-12-01'),
    applyUrl: 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html',
    sourceUrl: 'https://www.sbfi.admin.ch/',
    sourceDomain: 'sbfi.admin.ch',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Swiss Government Excellence Scholarships provide researchers and artists from abroad with the opportunity to pursue research or further training in Switzerland at one of the public funded university.',
    eligibility: 'Must have a master\'s degree. Under 35 years old. Research scholarships for doctoral or post-doctoral research.',
    tags: ['fully-funded', 'switzerland', 'phd', 'postdoc', 'research', 'europe'],
  },
  {
    title: 'Turkiye Burslari (Turkey Scholarships)',
    sponsor: 'Republic of Türkiye',
    orgType: 'government',
    hostCountry: 'Turkey',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['bachelors', 'masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: true, visa: false, stipendAmount: '₺3,500-7,000/month' },
    deadline: new Date('2027-02-20'),
    applyUrl: 'https://turkiyeburslari.gov.tr/',
    sourceUrl: 'https://turkiyeburslari.gov.tr/',
    sourceDomain: 'turkiyeburslari.gov.tr',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Türkiye Scholarships is a government-funded, competitive scholarship program, awarded to outstanding students and researchers to pursue full-time or short-term programs in top Turkish universities.',
    eligibility: 'Non-Turkish citizen, under 21 for bachelors, under 30 for masters, under 35 for PhD. Strong academic record.',
    tags: ['fully-funded', 'turkey', 'bachelors', 'masters', 'phd', 'middle-east'],
  },
  {
    title: 'New Zealand Scholarships (Manaaki)',
    sponsor: 'New Zealand Ministry of Foreign Affairs and Trade',
    orgType: 'government',
    hostCountry: 'New Zealand',
    eligibleCountries: ['Indonesia', 'Philippines', 'Vietnam', 'Papua New Guinea', 'Fiji', 'Samoa', 'Tonga', 'Timor-Leste', 'Myanmar', 'Laos'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: true, stipendAmount: 'NZD 550/week' },
    deadline: new Date('2027-03-28'),
    applyUrl: 'https://www.mfat.govt.nz/en/aid-and-development/new-zealand-government-scholarships/manaaki-new-zealand-scholarships/',
    sourceUrl: 'https://www.mfat.govt.nz/',
    sourceDomain: 'mfat.govt.nz',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Manaaki New Zealand Scholarships are for candidates from eligible countries to undertake full-time tertiary education study in New Zealand at participating institutions.',
    eligibility: 'Citizen of an eligible country, not currently holding NZ citizenship/residency, meet English language requirements.',
    tags: ['fully-funded', 'new-zealand', 'masters', 'phd', 'oceania'],
  },
  {
    title: 'Vanier Canada Graduate Scholarships',
    sponsor: 'Government of Canada',
    orgType: 'government',
    hostCountry: 'Canada',
    eligibleCountries: [],
    disciplines: ['Health Research', 'Natural Sciences', 'Engineering', 'Social Sciences', 'Humanities'],
    degreeLevel: ['phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: false, travel: false, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: 'CAD $50,000/year for 3 years' },
    deadline: new Date('2026-11-01'),
    applyUrl: 'https://vanier.gc.ca/en/nomination_process-processus_de_mise_en_candidature.html',
    sourceUrl: 'https://vanier.gc.ca/',
    sourceDomain: 'vanier.gc.ca',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Vanier Canada Graduate Scholarships program aims to attract and retain world-class doctoral students by supporting students who demonstrate leadership skills and a high standard of scholarly achievement.',
    eligibility: 'Nominated by a Canadian university. Must be in first 20 months of PhD. Both Canadian and international students eligible.',
    tags: ['fully-funded', 'canada', 'phd', 'research', 'prestigious'],
  },
  {
    title: 'Rhodes Scholarship (Oxford)',
    sponsor: 'Rhodes Trust',
    orgType: 'ngo',
    hostCountry: 'United Kingdom',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'South Africa', 'Zimbabwe', 'India', 'Pakistan', 'United States', 'Canada', 'Australia', 'Germany'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: '£18,180/year' },
    deadline: new Date('2026-10-01'),
    applyUrl: 'https://www.rhodeshouse.ox.ac.uk/scholarships/apply/',
    sourceUrl: 'https://www.rhodeshouse.ox.ac.uk/scholarships/',
    sourceDomain: 'rhodeshouse.ox.ac.uk',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Rhodes Scholarship is the oldest and most celebrated international fellowship award in the world. Rhodes Scholars study at the University of Oxford.',
    eligibility: 'Between 18 and 28 years old at the time of application. Bachelor\'s degree. Outstanding academic achievement, leadership, and commitment to service.',
    tags: ['fully-funded', 'uk', 'oxford', 'masters', 'phd', 'prestigious', 'leadership'],
  },
  {
    title: 'Schwarzman Scholars Program',
    sponsor: 'Schwarzman Education Foundation',
    orgType: 'ngo',
    hostCountry: 'China',
    eligibleCountries: [],
    disciplines: ['Public Policy', 'Economics', 'Business', 'International Studies'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: true, visa: false, stipendAmount: 'Included' },
    deadline: new Date('2026-09-15'),
    applyUrl: 'https://www.schwarzmanscholars.org/admissions/',
    sourceUrl: 'https://www.schwarzmanscholars.org/',
    sourceDomain: 'schwarzmanscholars.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Schwarzman Scholars is a highly selective, fully-funded one-year master\'s program at Tsinghua University in Beijing, designed to prepare young leaders for a world where China plays an increasingly important role.',
    eligibility: 'Between 18 and 28 years old. Bachelor\'s degree by August of enrollment year. English proficiency required. No Chinese language required.',
    tags: ['fully-funded', 'china', 'masters', 'leadership', 'prestigious', 'asia'],
  },
  {
    title: 'Aga Khan Foundation International Scholarship Programme',
    sponsor: 'Aga Khan Foundation',
    orgType: 'ngo',
    hostCountry: 'Multiple Countries',
    eligibleCountries: ['Kenya', 'Tanzania', 'Uganda', 'Mozambique', 'Madagascar', 'Pakistan', 'India', 'Bangladesh', 'Afghanistan', 'Tajikistan', 'Kyrgyzstan', 'Syria', 'Egypt'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters'],
    fundingType: 'partial',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: '50% grant, 50% loan' },
    deadline: new Date('2027-03-31'),
    applyUrl: 'https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme',
    sourceUrl: 'https://www.akdn.org/',
    sourceDomain: 'akdn.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Aga Khan Foundation provides a limited number of scholarships each year for postgraduate studies to outstanding students from developing countries who have no other means of financing their studies.',
    eligibility: 'From an eligible developing country, demonstrate financial need, excellent academic record, under 30 years old.',
    tags: ['partial-funding', 'international', 'masters', 'financial-need'],
  },
  {
    title: 'Rotary Peace Fellowship',
    sponsor: 'Rotary Foundation',
    orgType: 'ngo',
    hostCountry: 'Multiple (US, Japan, UK, Australia, Sweden)',
    eligibleCountries: [],
    disciplines: ['Peace Studies', 'Conflict Resolution', 'International Relations', 'Development Studies'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: false, accommodation: true, visa: false, stipendAmount: 'All expenses covered' },
    deadline: new Date('2027-05-15'),
    applyUrl: 'https://www.rotary.org/en/our-programs/peace-fellowships',
    sourceUrl: 'https://www.rotary.org/',
    sourceDomain: 'rotary.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Each year, Rotary selects up to 130 individuals from around the world to receive fully funded academic fellowships at one of our peace centers in five countries.',
    eligibility: 'Minimum 3 years of full-time work or volunteer experience in peace and development. Strong English proficiency.',
    tags: ['fully-funded', 'peace', 'masters', 'international', 'work-experience-required'],
  },
  {
    title: 'Netherlands Fellowship Programmes (NFP/OKP)',
    sponsor: 'Dutch Ministry of Foreign Affairs (Nuffic)',
    orgType: 'government',
    hostCountry: 'Netherlands',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'Ethiopia', 'Tanzania', 'Uganda', 'Mozambique', 'Bangladesh', 'Indonesia', 'Vietnam', 'Egypt', 'South Africa'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: true, stipendAmount: '€1,050/month' },
    deadline: new Date('2027-03-01'),
    applyUrl: 'https://www.nuffic.nl/en/subjects/orange-knowledge-programme',
    sourceUrl: 'https://www.nuffic.nl/',
    sourceDomain: 'nuffic.nl',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Orange Knowledge Programme (OKP) strengthens organisations in partner countries by making knowledge and education in the Netherlands accessible.',
    eligibility: 'From an OKP partner country, working for an organization, minimum 2 years professional experience, sponsored by employer.',
    tags: ['fully-funded', 'netherlands', 'masters', 'europe', 'work-experience-required'],
  },
  {
    title: 'Swedish Institute Scholarships for Global Professionals (SISGP)',
    sponsor: 'Swedish Institute',
    orgType: 'government',
    hostCountry: 'Sweden',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'Ethiopia', 'Tanzania', 'Uganda', 'Bangladesh', 'Indonesia', 'Cambodia', 'Colombia', 'Peru', 'Bolivia'],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: 'SEK 10,000/month' },
    deadline: new Date('2027-02-10'),
    applyUrl: 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/',
    sourceUrl: 'https://si.se/',
    sourceDomain: 'si.se',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'SISGP targets professionals from eligible countries who want to pursue full-time master\'s studies in Sweden. The scholarship covers tuition, living expenses, and travel grant.',
    eligibility: 'From an eligible country, minimum 3,000 hours work experience, admitted to eligible Swedish master\'s programme, demonstrate leadership.',
    tags: ['fully-funded', 'sweden', 'masters', 'europe', 'work-experience-required', 'leadership'],
  },
  {
    title: 'World Bank Scholarship Program (JJ/WBGSP)',
    sponsor: 'World Bank Group',
    orgType: 'international',
    hostCountry: 'Multiple Countries',
    eligibleCountries: [],
    disciplines: ['Development Economics', 'Public Health', 'Education', 'Agriculture', 'Environmental Science', 'Infrastructure', 'Public Administration'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: 'Varies by institution' },
    deadline: new Date('2027-04-08'),
    applyUrl: 'https://www.worldbank.org/en/programs/scholarships',
    sourceUrl: 'https://www.worldbank.org/',
    sourceDomain: 'worldbank.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The JJ/WBGSP offers scholarships to developing country nationals who have relevant professional experience and a history of supporting their communities\' development efforts.',
    eligibility: 'From a developing World Bank member country, minimum 3 years professional experience in development, employer sponsorship.',
    tags: ['fully-funded', 'international', 'masters', 'development', 'work-experience-required'],
  },
  {
    title: 'Eiffel Excellence Scholarship (France)',
    sponsor: 'French Ministry of Europe and Foreign Affairs',
    orgType: 'government',
    hostCountry: 'France',
    eligibleCountries: [],
    disciplines: ['Engineering', 'Science', 'Economics', 'Management', 'Law', 'Political Science'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: false, visa: false, stipendAmount: '€1,181/month (masters) or €1,700/month (PhD)' },
    deadline: new Date('2027-01-10'),
    applyUrl: 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence',
    sourceUrl: 'https://www.campusfrance.org/',
    sourceDomain: 'campusfrance.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Eiffel Excellence Scholarship Program was established by the French Ministry of Foreign Affairs to attract top international students to French higher education institutions.',
    eligibility: 'Non-French citizen, under 25 for master\'s, under 30 for PhD. Must apply through a French higher education institution.',
    tags: ['fully-funded', 'france', 'masters', 'phd', 'europe', 'prestigious'],
  },
  {
    title: 'Denning Scholarship (Said Business School, Oxford)',
    sponsor: 'University of Oxford',
    orgType: 'university',
    hostCountry: 'United Kingdom',
    eligibleCountries: [],
    disciplines: ['MBA', 'Business', 'Management'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: false, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: 'Tuition + £15,000 living costs' },
    deadline: new Date('2027-01-06'),
    applyUrl: 'https://www.sbs.ox.ac.uk/programmes/mba/fees-funding/scholarships',
    sourceUrl: 'https://www.sbs.ox.ac.uk/',
    sourceDomain: 'sbs.ox.ac.uk',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Denning Scholarship is for aspiring entrepreneurs. It covers full tuition fees and a grant for living costs for the one-year MBA programme at Saïd Business School, University of Oxford.',
    eligibility: 'Admitted to the Oxford MBA programme, demonstrate entrepreneurial ambition, open to all nationalities.',
    tags: ['fully-funded', 'uk', 'oxford', 'mba', 'business', 'entrepreneurship'],
  },
  {
    title: 'Clarendon Fund Scholarships (Oxford)',
    sponsor: 'University of Oxford',
    orgType: 'university',
    hostCountry: 'United Kingdom',
    eligibleCountries: [],
    disciplines: ['All disciplines'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: false, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: '£18,622/year' },
    deadline: new Date('2027-01-15'),
    applyUrl: 'https://www.ox.ac.uk/clarendon/',
    sourceUrl: 'https://www.ox.ac.uk/clarendon/',
    sourceDomain: 'ox.ac.uk',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The Clarendon Fund is the University of Oxford\'s flagship scholarship scheme offering around 140 new scholarships every year across all academic divisions.',
    eligibility: 'Automatically considered when you apply for graduate study at Oxford. Outstanding academic merit and potential.',
    tags: ['fully-funded', 'uk', 'oxford', 'masters', 'phd', 'automatic-consideration'],
  },
  {
    title: 'ETH Zurich Excellence Scholarship',
    sponsor: 'ETH Zurich',
    orgType: 'university',
    hostCountry: 'Switzerland',
    eligreeLevel: ['masters'],
    disciplines: ['Engineering', 'Computer Science', 'Mathematics', 'Natural Sciences', 'Architecture'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: false, living: true, insurance: false, accommodation: false, visa: false, stipendAmount: 'CHF 12,000/semester + tuition waiver' },
    deadline: new Date('2026-12-15'),
    applyUrl: 'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html',
    sourceUrl: 'https://ethz.ch/',
    sourceDomain: 'ethz.ch',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'The ETH Zurich Excellence Scholarship & Opportunity Programme (ESOP) supports excellent students wishing to pursue their Master\'s degree at ETH Zurich.',
    eligibility: 'Excellent academic record (top 10% of bachelor\'s class), admitted to ETH Zurich master\'s program.',
    tags: ['fully-funded', 'switzerland', 'masters', 'stem', 'europe', 'prestigious'],
  },
  {
    title: 'KAUST Fellowship (King Abdullah University)',
    sponsor: 'King Abdullah University of Science and Technology',
    orgType: 'university',
    hostCountry: 'Saudi Arabia',
    eligibleCountries: [],
    disciplines: ['Engineering', 'Computer Science', 'Biological Science', 'Physical Science', 'Mathematics'],
    degreeLevel: ['masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: true, visa: true, stipendAmount: '$20,000-30,000/year' },
    deadline: new Date('2027-01-15'),
    applyUrl: 'https://www.kaust.edu.sa/en/study/applying-to-kaust',
    sourceUrl: 'https://www.kaust.edu.sa/',
    sourceDomain: 'kaust.edu.sa',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'KAUST offers one of the most generous fellowship packages in the world. All admitted students receive full fellowship covering tuition, housing, and a monthly living allowance.',
    eligibility: 'Bachelor\'s degree in STEM field, strong academic record, English proficiency (TOEFL/IELTS). Open to all nationalities.',
    tags: ['fully-funded', 'saudi-arabia', 'masters', 'phd', 'stem', 'middle-east'],
  },
  {
    title: 'Stipendium Hungaricum Scholarship',
    sponsor: 'Government of Hungary',
    orgType: 'government',
    hostCountry: 'Hungary',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'Ethiopia', 'Tanzania', 'India', 'Pakistan', 'Bangladesh', 'Vietnam', 'Indonesia', 'Jordan', 'Tunisia', 'Morocco', 'Egypt'],
    disciplines: ['All disciplines'],
    degreeLevel: ['bachelors', 'masters', 'phd'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: false, living: true, insurance: true, accommodation: true, visa: false, stipendAmount: 'HUF 140,000-180,000/month' },
    deadline: new Date('2027-01-15'),
    applyUrl: 'https://stipendiumhungaricum.hu/',
    sourceUrl: 'https://stipendiumhungaricum.hu/',
    sourceDomain: 'stipendiumhungaricum.hu',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'Stipendium Hungaricum is a scholarship programme launched in 2013 by the Hungarian Government. The programme aims to increase the number of foreign students in Hungary.',
    eligibility: 'From a sending partner country. Meet the academic requirements of the chosen programme. Medical fitness.',
    tags: ['fully-funded', 'hungary', 'bachelors', 'masters', 'phd', 'europe'],
  },
  {
    title: 'AfDB Japan Africa Dream Scholarship (JADS)',
    sponsor: 'African Development Bank & Government of Japan',
    orgType: 'international',
    hostCountry: 'Japan',
    eligibleCountries: ['Nigeria', 'Ghana', 'Kenya', 'Ethiopia', 'Tanzania', 'South Africa', 'Egypt', 'Morocco', 'Senegal', 'Cameroon', 'Rwanda'],
    disciplines: ['Development Studies', 'Engineering', 'Agriculture', 'Environmental Science', 'Economics', 'Public Health'],
    degreeLevel: ['masters'],
    fundingType: 'fully_funded',
    coverageDetails: { tuition: true, travel: true, living: true, insurance: true, accommodation: true, visa: false, stipendAmount: '¥150,000/month' },
    deadline: new Date('2027-04-30'),
    applyUrl: 'https://www.afdb.org/en/about-us/careers/japan-africa-dream-scholarship-jads-program',
    sourceUrl: 'https://www.afdb.org/',
    sourceDomain: 'afdb.org',
    trustTier: 1,
    scamFlag: false,
    verificationStatus: 'verified',
    description: 'JADS is a scholarship programme established by the AfDB and the Government of Japan. It enables African students to pursue master\'s degree studies in priority development areas at Japanese universities.',
    eligibility: 'National of an African Development Bank member country, under 35 years old, minimum 2 years professional experience, employed by a development institution.',
    tags: ['fully-funded', 'japan', 'africa', 'masters', 'development', 'asia'],
  },
];

async function main() {
  console.log('Seeding opportunities...');
  
  // Clear existing
  await prisma.opportunity.deleteMany();
  
  for (const opp of opportunities) {
    // Remove any accidental extra fields
    const { eligreeLevel, ...cleanOpp } = opp as any;
    await prisma.opportunity.create({ data: cleanOpp });
  }
  
  console.log(`✅ Seeded ${opportunities.length} verified opportunities into Supabase.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
